export const speakers = [
  {
    id: "1",
    image: "/images/speakers/ccd8c70926a25b9c4fb841f8b0d79561ae68f3db.avif",
    name: "Bernardo A. Saenz",
    role: "Cofundador Fortaleciendo",
    company: "Junta Directiva AFENCO",
    description: "Docente y Speaker especializado en fortalecimiento empresarial",
    tags: ["Liderazgo", "Gestión Empresarial"],
    tagsBelow: ["Liderazgo", "Gestion Empresarial", "Desarrollo Organizacional"],
    country:"Colombia",
  },
  {
    id: "2",
    image: "",
    name: "Sebastián Gallego",
    role: "Creador de contenido",
    company: "Empresario Digital",
    description: "Exporto en marketing y creacion de contenido empresarial",
    tags: ["Marketing Digital", "Contenido"],
    tagsBelow: ["Marketing Digital", "Contenido", "Redes Sociales"],
    country:"Colombia",
  },
  {
    id: "3",
    image: "",
    name: "Johana Escamilla",
    role: "Docente Uniquindio",
    company: "Especialista en Educación",
    description: "Profesora universitaria con amplia experiencia en formacion empresarial",
    tags: ["Educación", "Capacitación"],
    tagsBelow: ["Educacion", "Capacitacion", "Desarrollo Academico"],
    country:"Colombia",
  },
  {
    id: "4",
    image: "",
    name: "Winston Yandun",
    role: "Speaker Internacional",
    company: "Coach & Trainer",
    description: "Coach empresarial con experiencia internacional en desarrollo de liderazgo",
    tags: ["Coaching", "Liderazgo"],
    tagsBelow: ["Coaching", "Liderazgo", "Desarrollo Personal"],
    country:"Colombia",
  },
  {
    id: "5",
    image: "",
    name: "Nelson Segura",
    role: "Abogado Especialista",
    company: "Seguridad Social",
    description: "Experto en derecho laboral y seguridad social empresarial",
    tags: ["Derecho Laboral", "Seguridad Social"],
    tagsBelow: ["Derecho Laboral", "Seguridad Social", "Consultoria Legal"],
    country:"Colombia",
  },
  {
    id: "6",
    image: "",
    name: "Gustavo Zabala",
    role: "CEO EPIC Digital",
    company: "Lider CEMPRENDE Quindio",
    description: "Emprendedro y lider en trasformacion digital empresarial",
    tags: ["Trasformacion Digital", "Emprendimiento"],
    tagsBelow: ["Trasformacion Digital", "Emprendimiento", "innovacion"],
    country:"Colombia",
  },
];

export function getSpeakerById(id){
  return speakers.find((s)=> s.id ===id);
}